# Aggregate Data and Standard Features Extracted from a Decade of Job Ads

Welcome to the demonstration notebook for the PNAS article: *Aggregate Data and Standard Features Extracted from a Decade of Job Ads*!

The goal of this demonstration is to walk you through the basic usage of all of the JAAT modules, as described in the paper. To do this, we will introduce and develop a working example using USAJOBS data, which we have also open-sourced to enable a reproduction of the analyses we present in the paper.

We have left the outputs pre-filled, but we encourage you to run on your own.

Thank you for checking JAAT out, and here we go!

## Getting Started

First, we will import all of the necessary tools to run JAAT on USAJOBS data. In case you have not already, install all the required dependencies, either via your system or by running the command directly below (uncomment and replace with the correct path).

In [2]:
# !pip install /path/to/requirements.txt

And now for the imports:

In [2]:
import pandas as pd
import numpy as np
from datasets import load_dataset

### USAJOBS Data

Let's first get familiar with the USAJOBS dataset we provide. The entire corpus comprise federal job postings from 2017-01 to 2026-03, but for now, we will work on a smaller random sample of 1000 job postings -- this we also provide in our open-source dataset.

In [3]:
sample = load_dataset("loyoladatamining/usajobs", "sample", split="sample")

The above command loads the dataset from Hugging Face, but for ease, we will convert it to a Pandas DataFrame and explore its makeup.

In [4]:
df = sample.to_pandas()
df

,job_id,text,title,company
0,767977200,USAJOBS - Job Announcement family-of-overseas-...,Information Technology Specialist (Policy and ...,None
1,764460600,USAJOBS - Job Announcement family-of-overseas-...,Lead Security Guard,None
2,767905500,USAJOBS - Job Announcement family-of-overseas-...,Lead Recreation Assistant NF-02,None
3,765868200,USAJOBS - Job Announcement family-of-overseas-...,Medical Administrative Specialist,None
4,767266900,USAJOBS - Job Announcement family-of-overseas-...,PROGRAM MANAGER (INFORMATION RESOURCES),None
...,...,...,...,...
995,764122300,USAJOBS - Job Announcement family-of-overseas-...,PROGRAM ANALYST,None
996,764459600,USAJOBS - Job Announcement family-of-overseas-...,CYS Program Associate Technology Lab NF-03,None
997,763842000,USAJOBS - Job Announcement family-of-overseas-...,Licensed Practical Nurse,None
998,767090700,USAJOBS - Job Announcement family-of-overseas-...,SUPERVISORY EDUCATION SERVICES SPECIALIST,None
999,765471900,USAJOBS - Job Announcement family-of-overseas-...,Health System Specialist (Detail NTE 120 Days),None

In [5]:
# see what columns are included
df.columns

Index(['job_id', 'text', 'title', 'company'], dtype='object')

In [6]:
# view a selected job title
df.title.iloc[42]

'Visual Information Specialist (Marketing Assistant)'

In [7]:
# view the above's corresponding job posting text
df.text.iloc[42]

'USAJOBS - Job Announcement family-of-overseas-employees-icon federal-employees-competitive-service-icon federal-employees-competitive-service-icon federal-employees-excepted-service-icon federal-employees-career-transition-icon individuals-with-disabilities-icon Created with Sketch. internal-to-an-agency-icon Created with Sketch. internal-to-an-agency-icon Created with Sketch. military-spouses-icon Created with Sketch. national-guard-and-reserves-icon Created with Sketch. native-americans-icon Created with Sketch. peace-corps-and-americorps-icons Open-to-the-public-icon senior-executive-service-icon se-other students-icon recent-graduates-icon veterans-icon special-hiring-authorities-icon land-and-base-management-icon Visual Information Specialist (Marketing Assistant) Department of the Navy Commander, Navy Installations CNRSE NAVAL AIR STATION JACKSONVILLE N922 Help Summary This position is located in the Morale, Welfare and Recreation (MWR) Marketing Department aboard Naval Air Station Jacksonville, Florida. The purpose of this position is to support the Marketing/Sponsorship Program by designing and implementing diversified media packages that enhances and promote facility and recreational programs to support the quality of life and mission readiness of active duty military members and their families. Help Overview Hiring complete Open & closing dates 12/29/2023 to 01/07/2024 Salary $18 - $22 per hour Pay scale & grade NF 3 Location 1 vacancy in the following location: Naval Air Station Jacksonville, FL Remote job No Telework eligible No Travel Required Occasional travel - You may be expected to travel for this position. Relocation expenses reimbursed No Appointment type Permanent Work schedule Full-time Service Competitive Promotion potential 3 Job family (Series) 1084 Visual Information Supervisory status No Security clearance Other Drug test No Position sensitivity and risk Non-sensitive (NS)/Low Risk Trust determination process Suitability/Fitness Announcement number JAX-24-12260198 Control number 768218800 Help This job is open to The public U.S. Citizens, Nationals or those who owe allegiance to the U.S. Clarification from the agency Please see the "Who May Apply" section under the Qualifications section. Help Duties Identifies, establishes and maintains communication needs and develops informational material that inform appropriate agencies of the policies, services, and activities of the MWR Department. Assists supervisor with commercial sponsorship/advertising proposals, solicitation of potential sponsors, sponsorship agreements and after-action reports in ensuring that all stay within Navy policy and instructions. Responsible for designing, implementing and maintain social interactive applications sites, websites and smartphone app for MWR/CYP programs that push the MWR missions and markets NAS Jax MWR as a "customer driven" organization. Creates innovative marketing campaigns from inception to completion and is responsible for the production of graphic art services to MWR facilities. Plans and designs visual information material including but not limited to printed publications, photography, logs, flyers, posters, signs, banners, certificates and in some cases video promotional vehicles which will be used to promote the department and highlight or enhance program or events. Will evaluate the effectiveness of promotional documents/flyers and implements changes to positively improve the program quality, service and patronage. Maintains communication with the MWR Department Managers and Program Managers for input for all publications pertaining to individual facility activities/events. Executes the timely development, layout, writing proofing, printing and distribution of all MWR publications and advertisements while ensuring that the content is current, accurate, audience friendly and of high quality. Promotes the wide range of MWR activities for authorized patrons and guests through multiple media channels including but not limited to social media, digital displays, printed advertisement, electronic newsletter, website and smartphone app. Responsible for the implementation, design, content, scheduling and timely management of the electronic newsletter. Coordinates with the Marketing Director and program managers to plan, coordinate and conduct market research to include but may not be limited to utilizing demographic research, surveys, and/or focus groups. Researches and executes promotional ideas and items, marketing strategies and distribution plans. Presents MWR services and programs in pre-deployments briefs and Ombudsman meeting with the coordination for the overall design of an ongoing Indoctrination including conducting on-site briefing to military personnel reporting to the component and tenant commands supported by the NAS Jacksonville composite recreation fund. Responsible for ensuring that all bulletin boards and digital displays within tenant commands and MWR facilities are properly updated with MWR program, event, and promotional advertisements. Manages current response system for web-generated email, phone calls and regular mail, ensuring that responses are timely and that they reflect well on the Department. Prepares packages for sponsorship requests, meets with potential sponsors to promote opportunities, and facilitates support for sponsor during programs. Serves on command committees to ascertain needs, solicits feedback and introduce ideas. Stays current with the latest graphic design programs, user interface and web technology trends and passes this information on to immediate supervisor. Ensures integrity of communications by keeping informed on legislation and DOD policies that affect Internet and website content. Completes other related duties as assigned within the escope of the position. Help Requirements Conditions of Employment Must meet Federal Employment suitability requirements and successful completion of background investigation.  Background investigations are conducted using fingerprint identification and completion of background inquiry forms. Must successfully pass the E-verify employment verification check.  Any discrepancies must be resolved as a condition of employment. You must go through a Personal Identity Verification (PIV) process that requires two forms of identification from the Form I-9. May be required to pass pre-employment examinations. Must provide proof of U.S. Citizenship or U.S. National. A valid State driver\'s license is required to operate motor vehicles. Must have your salary sent to a financial institution of your choice by Direct Deposit/Electronic Funds Transfer. Must be physically able to stand, bend, stoop and walk in performance of work. Must be able to work both indoor and outdoor. Must be able to lift up to 45 pounds with or without assistance. Qualifications In order to qualify for this position, your resume must provide sufficient experience and/or education, knowledge, skills, and abilities, to perform the duties of the specific position for which you are being considered. Your resume is the key means we have for evaluating your skills, knowledge, and abilities, as they relate to this position. Therefore, we encourage you to be clear and specific when describing your experience. All non-government positions identified on your resume must include complete address and to and from dates. Government positions must include pay plan, series, grade, to and from dates and address of the agency/organization. Five + years of related experience in multimedia and web design OR a four year Bachelors\' degree in related field that demonstrates knowledge and application of website design, graphic arts and other visual media and above average working knowledge of marketing principles, techniques and methods to develop, implement and maintain an effective marketing program. Skilled in various computer and software programs to include but not limited to Adobe Acrobat X Pro, Illustrator, Photoshop, InDesign, Microsoft Outlook, PowerPoint, Publisher, Word and Excel. Must be proficient in designing, establishing, and maintaining all forms of social media and accompanying smartphone apps. In-depth knowledge of software that runs on the internet including but not limited to search engines, browsers, databases, plug-ins, and applets. Must have excellent written and oral communication skills, administrative support and strong organization skills and have the ability to speak clearly in front of large and diverse groups of people. Possess and maintain above average working knowledge of design software programs, social media technology and industry standard marketing and digital practices to most effectively meet the promotional objectives of the department. In-depth knowledge of graphic design programs, desktop publishing and web design software including but not limited to Adobe Acrobat Pro, Illustrator, Photoshop and InDesign. Must possess the passion for learning and staying current with the latest web/graphic software, user interface, web technology trends and can teach it to others. Ability to research, plan and design visual information material including but not limited to printed publications, photography, logos, flyers, electronic newsletter, signs, banners and in some cases video promotional vehicles which will be used to promote the department and highlight or enhance program or events. Evaluates effectiveness, and implements changes to positively improve program quality, service and patronage. Can skillfully translate graphically designed media into digital marketing campaigns for social media outlets, electronic newsletter, website, smartphone app and digital displays within facilities. Ability to quickly grasp communication objectives, to summarize them and develop an appropriate interactive media plan. Must possess above-average skill to communicate effectively, both orally and in writing to write grammatically correct news and feature stories, cut lines, press releases, and presentation in combination with photography as well as to professionally draft sponsorship solicitation, letters, packages, proposals and presentations. Ability to prioritize and multi-task, ensuring all deadlines are met. You will receive credit for all qualifying experience, including volunteer and part time experience. You must clearly identify the duties and responsibilities in each position held and the total number of hours per week. Experience refers to paid and unpaid experience, including volunteer work done through National Service programs (e.g., professional, philanthropic, religious, spiritual, community, student, social). Volunteer work helps build critical competencies, knowledge, and skills and can provide valuable training and experience that translates directly to paid employment. As part of the application process, you must complete and submit an occupational questionnaire and your RESUME MUST SUPPORT AND VALIDATE YOUR ANSWERS or you may be removed from consideration. ONLY THE MOST HIGHLY QUALIFIED CANDIDATES WILL BE REFERRED. IF MANAGEMENT DOES NOT WISH TO SELECT A HIGHLY QUALIFIED CANDIDATE, THEY MAY REQUEST A REFERRAL LIST INCLUDING WELL OR QUALIFIED APPLICANTS. Please follow all instructions carefully. Errors or omissions may affect your rating and/or appointment eligibility. PLEASE READ THIS VACANCY ANNOUNCEMENT IN ITS ENTIRETY TO ENSURE ALL REQUIREMENTS ARE ADDRESSED IN YOUR APPLICATION PACKAGE. RELOCATION NOT AUTHORIZED NO Payment of Permanent Change of Station (PCS) is authorized, based on a determination that a PCS move is not in the Government interest. KEY REQUIREMENTS/CONDITIONS OF EMPLOYMENT You must be a US Citizen. Males must be registered or exempt from Selective Service. https://www.sss.gov/register/ Selectee must be determined suitable for federal employment. Selectee may be required to successfully complete a probationary period. Selectee is required to participate in the direct deposit pay program. Social Security Card is required. Satisfactorily complete an employment verification (E-VERIFY) check. A favorable background is a requirement of this position. Failure to obtain and maintain a favorable background may result in the withdrawal of the position offer or removal. NOTE: Applicants have the ability to perform an E-Verify Self Check to confirm employment eligibility at http://www.uscis.gov/mye-verify/self-check . Although a Self-Check is not mandatory, it can be a useful tool for applicants to find out if there is a problem with their employment eligibility records and resolve any issues before taking a job. Education A Bachelor\'s degree from an accredited university in related field is preferred. Additional information The Federal government offers a number of exceptional benefits to its employees.  Benefits you get to enjoy while working for our TEAM include but are not limited to: Comprehensive benefits package (medical, dental, life insurance, spouse & dependent life insurance, long-term disability, retirement, and 401(k) savings plan, annual and sick leave, tuition reimbursement, etc.). Stability of Federal Civilian Service People with passion for doing work that matters Quality of Work Life Balance Some positions have special requirements- Position is a non-critical, sensitive, position requiring access to IT II system and/or access to PII. An access National Agency Check investigation (ANACI) is required via the SF 86 security form.- Required to submit a Financial Disclosure Statement, OGE-450. Executive Branch Personnel Confidential Financial Disclosure Report upon entering the position and annually, in accordance with DoD Directive 5500-7R, Joint Ethics Regulation, dated 23 March 2006.- Salary is dependent on experience and/or education.- For positions requiring travel more than twice per year, selectee may be required to obtain and maintain in good standing a Government-issued Travel Card for official government travel purposes. This announcement may be used to fill additional vacancies within 90 days of closing date. The Department of the Navy (DON) is an Equal Employment Opportunity Employer. Applicants are assured of equal consideration regardless of race, color, national origin, religion, sex, age, mental or physical disability, genetic information, reprisal, marital status, political affiliation, sexual orientation, or any other non-merit factor. This agency provides reasonable accommodations to applicants with disabilities.  Applicants with disabilities who believe they may require reasonable accommodations should email their request to MILL_CNIC_NAF_EEO@navy.mil to ensure proper consideration is given.  The decision on granting reasonable accommodation will be on a case-by-case basis. This activity is a Drug-Free workplace.  The use of illegal drugs by NAF employees, whether on or off duty, cannot and will not be tolerated.  Federal employees have a right to a safe and secure workplace, and Sailors, their family members, and all other customers have a right to a reliable and productive Federal workforce. Benefits A career with the U.S. government provides employees with a comprehensive benefits package. As a federal employee, you and your family will have access to a range of benefits that are designed to make your federal career very rewarding. Opens in a new window Learn more about federal benefits . Review our benefits Eligibility for benefits depends on the type of position you hold and whether your position is full-time, part-time or intermittent. Contact the hiring agency for more information on the specific benefits offered. How You Will Be Evaluated You will be evaluated for this job based on how well you meet the qualifications above. Your experience is subject to evaluation and verification against the information in your resume.  The numeric rating you receive is a self-assessment only and is based on your responses to the questionnaire.  Do not overstate or understate your level of experience and capability.  If a determination is made that you rated yourself higher than is supported by your resume, or if your resume lacks sufficient information, you will be rated accordingly or may be considered ineligible. All resumes will be reviewed to determine if they meet the hiring eligibility and qualification requirements listed in this announcement, and will be rated based on the information provided in the resume to determine the level of knowledge, skill, and ability, related to the job requirements. Using the qualifications of the position, a predetermined rating criterion of knowledge, skills, and abilities will be used for each resume. Best qualified applicants will be referred to the hiring manager. The selecting official may choose to conduct interviews. Benefits A career with the U.S. government provides employees with a comprehensive benefits package. As a federal employee, you and your family will have access to a range of benefits that are designed to make your federal career very rewarding. Opens in a new window Learn more about federal benefits . Review our benefits Eligibility for benefits depends on the type of position you hold and whether your position is full-time, part-time or intermittent. Contact the hiring agency for more information on the specific benefits offered. Required Documents As a new or existing federal employee, you and your family may have access to a range of benefits. Your benefits depend on the type of position you have - whether you\'re a permanent, part-time, temporary or an intermittent employee. You may be eligible for the following benefits, however, check with your agency to make sure you\'re eligible under their policies. -Resume -Include name and contact information for at least three (3) professional references in your resume -OF-306. http://www.opm.gov/forms/pdf_fill/OF0306.pdf -Proof of education (transcripts/copy of degree/high school diploma), if applicable to position requirements. -Proof of certification, if applicable to position requirements. -If you are a current federal employee, submit your most recent Personnel Action Report (PAR) or SF-50. -If you are a current federal employee, submit your last three evaluations. APPLICANTS CLAIMING HIRING PREFERENCE: Please ensure your status is indicated in your USAJOBS account and ALL required documents to claim preference are submitted at the time of resume submission. WHAT ARE PREFERENCES? Preferences are advantages in the candidate selection process. Individuals can claim the following preferences: 1. Reemployment Priority List (RPL): Qualifying separated employees shall have priority placement in the NAF activity from which they were separated as a result of a Business Based Action (BBA), when the position has substantially the same duties as the position from which they were separated and it is not a higher grade or employment category, provided the position is not being filled by an internal candidate. To claim this preference, you MUST: -Submit a copy of your BBA Separation Notification indicating eligibility for RPL. 2. Military Spouse Preference (MSP): Qualifying spouses eligible for MSP are spouses of an active duty military member of the U.S. Armed Forces, including members of the National Guard or Reserves on active duty. The marriage must have occurred before the military member received official permanent change of station (PCS) orders to the installation listed above. MSP is applicable only when applying for NAF positions at the NF-03 and below and equivalent craft and trade (CT) positions. To claim this preference, you MUST: -Submit sponsor\'s PCS orders to installation you are applying for; AND -If you are not indicated as a spouse on the PCS orders, you MUST submit proof of marriage prior to PCS. 3. Veteran\'s Preference/Gold Star Veteran\'s Preference: Qualifying military veterans, and spouses/parents of deceased veterans shall be given employment preference over non-preference applicants i

### JAAT

JAAT, or the *Job Ad Analysis Toolkit* is a modular collection of tools built to extract structured information form job posting text, from task requirements to wage statements to firm names. Below, we will walk through the basic usage of each of the tools we introduce in the paper, demonstrating their ease of use, speed, and structured outputs.

NOTE: we *highly* recommend running this notebook on a machine equipped with a GPU. While JAAT is fully functional on CPU-only setups as well, a GPU will make things go a whole lot quicker!

With that said, let us import the JAAT library. It is as easy as:

In [8]:
import JAAT

In JAAT, we have included some useful utilities to make sure your setup is ready to go.

In [9]:
# run a diagnostic to make sure JAAT recognizes your setup
JAAT.diagnostic()

--- JAAT Diagnostic Report ---
OS: Linux 6.6.87.2-microsoft-standard-WSL2
Python Version: 3.10.12 (main, Mar  3 2026, 11:56:32) [GCC 11.4.0]
PyTorch Version: 2.9.0+cu128
CUDA Available: True
GPU: NVIDIA RTX A6000
VRAM: 51.53 GB
Transformers Version: 4.57.6
------------------------------

In [10]:
# make sure the required files are there
JAAT.setup()

2026-05-14 10:22:30,727 - JAAT - INFO - --- JAAT Setup ---
2026-05-14 10:22:30,732 - JAAT - INFO - Checking JAAT data files...
2026-05-14 10:22:30,739 - JAAT - INFO - ✅ All internal data files present.
2026-05-14 10:22:30,744 - JAAT - INFO - ✅ CUDA detected! Using GPU: NVIDIA RTX A6000
2026-05-14 10:22:30,746 - JAAT - INFO -
--- Setup Complete ---

In [11]:
# toggle progress bars (if you want!)
JAAT.toggle_progress(True)

2026-05-14 10:22:31,455 - JAAT - INFO - JAAT progress bars are now enabled.

If all looks good with the setup steps, now is the time to dive into the JAAT modules. Let us first pick a representative job posting from our sample dataset.

In [12]:
test_posting = df.iloc[42].text
test_title = df.iloc[42].title
(test_title, test_posting)

('Visual Information Specialist (Marketing Assistant)',

Excellent. Now let us load up the first JAAT module: TaskMatch

TaskMatch extract task statements from job postings texts and matches these to standard O*NET codes.

To initialize TaskMatch, run the following (requires a few seconds on GPU to start up):

In [13]:
TM = JAAT.TaskMatch()

2026-05-14 10:22:37,864 - JAAT - INFO - Initalizing TaskMatch...
2026-05-14 10:22:37,866 - JAAT - INFO - Preparing embeddings...

Batches:   0%|          | 0/295 [00:00<?, ?it/s]

2026-05-14 10:22:46,385 - JAAT - INFO - Setting up pipeline...
Device set to use cuda
2026-05-14 10:22:46,680 - JAAT - INFO - Finished.

For most of the JAAT modules, we have built both a single-document mode and a batch mode. We will explore batching later, but first let us see the basic usage of TaskMatch.

In [14]:
TM.get_tasks(test_posting)

[('3242', 'Coordinate with the media to disseminate advertising.'),
 ('1552',
  'Provide information or technical or program assistance to government representatives, employers, or the general public on the issues of public health, environmental protection, or workplace safety.'),
 ('15600',
  'Maintain contact with sponsors to schedule and coordinate site visits or to answer questions about issues such as incomplete data.'),
 ('4000', 'Produce rough and finished graphics and graphic designs.'),
 ('9308',
  'Provide supportive materials for exhibits and displays, such as press kits, advertising, publicity notices, posters, brochures, catalogues, and invitations.'),
 ('7674', 'Develop promotions for current programs and specials.'),
 ('15816', 'Monitor and maintain records of daily facility operations.'),
 ('1783',
  'Oversee publication production, including artwork, layout, computer typesetting, and printing, ensuring adherence to deadlines and budget requirements.'),
 ('3932',
  'Host civic, charitable, or promotional events broadcast over television or radio.'),
 ('2813',
  'Operate electronic mail systems and coordinate the flow of information, internally or with other organizations.'),
 ('5439',
  'Conduct research on consumer opinions and marketing strategies, collaborating with marketing professionals, statisticians, pollsters, and other professionals.'),
 ('945',
  'Develop or implement product-marketing strategies, including advertising campaigns or sales promotions.'),
 ('14713',
  'Respond to user email inquiries, or set up automated systems to send responses.'),
 ('1225',
  'Design and implement efforts to publicize events and promote sponsorships.'),
 ('6490', 'Attend staff meetings and serve on committees as required.'),
 ('20377',
  'Research latest products, technology, or design trends to stay current in the field.'),
 ('21616', 'Document, and ensure communication of, key risks.'),
 ('9583',
  'Assign duties to other staff and give instructions regarding work methods and routines.'),
 ('23045',
  'Search for and collect evidence, such as fingerprints, using investigative equipment.'),
 ('14633', 'Design computers and the software that runs them.'),
 ('9261', 'Develop designs using specialized computer software.'),
 ('14701',
  'Maintain understanding of current Web technologies or programming practices through continuing education, reading, or participation in professional conferences, workshops, or groups.'),
 ('309',
  'Study illustrations and photographs to plan presentation of materials, products, or services.'),
 ('1130',
  'Evaluate the work of staff and volunteers to ensure that programs are of appropriate quality and that resources are used effectively.'),
 ('20321', 'Create content strategies for digital media.'),
 ('21230', 'Develop, implement, or maintain crisis communication plans.'),
 ('8839',
  'Deliver speeches, write articles, or present information at meetings or conventions to promote services, exchange ideas, or accomplish objectives.')]

Nice! We can see that the test posting includes many task statements. These have been returned by TaskMatch in a list of tuples, where each tuple takes the form of (TASK ID, TASK DESCRIPTION).

In a similar way, we can load and run SkillMatch, which is similar in makeup to TaskMatch but now identifies and extracts skill statements, coded accordingly to ESCO skill codes.

In [15]:
SM = JAAT.SkillMatch()

2026-05-14 10:22:51,067 - JAAT - INFO - Initializing SkillMatch...
2026-05-14 10:22:51,069 - JAAT - INFO - Preparing embeddings...

Batches:   0%|          | 0/28 [00:00<?, ?it/s]

2026-05-14 10:22:54,497 - JAAT - INFO - Setting up pipeline...
Device set to use cuda
2026-05-14 10:22:54,844 - JAAT - INFO - Finished.

In [16]:
SM.get_skills(test_posting)

[('developing instructive or promotional materials', 'S1.12'),
 ('draw up marketing and sales plan', 'S4.1'),
 ('driving vehicles', 'S8.2'),
 ('lift things', 'T5.1'),
 ('using word processing, publishing and presentation software', 'S5.6'),
 ('developing instructive or promotional materials', 'S1.12'),
 ('digital marketing', 'T1.3'),
 ('prioritise tasks', 'T3.1')]

In addition to extracting information from the job posting text itself, we have also built TitleMatch as a tool to match the job posting's stated job title to O*NET occupation titles.

Running TitleMatch is likewise straightforward:

In [17]:
TiM = JAAT.TitleMatch()

2026-05-14 10:22:59,334 - JAAT - INFO - Initializing TitleMatch...
2026-05-14 10:22:59,335 - JAAT - INFO - Loading data...
2026-05-14 10:22:59,521 - JAAT - INFO - Preparing embeddings...
2026-05-14 10:22:59,522 - JAAT - INFO - Loading title models...
Device set to use cuda
2026-05-14 10:23:01,867 - JAAT - INFO - Finished.

In [18]:
TiM.get_title(test_title)

2026-05-14 10:23:02,957 - JAAT - INFO - Extracting title values...

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

2026-05-14 10:23:03,220 - JAAT - INFO - Extracting title features...

Processing:   0%|          | 0/1 [00:00<?, ?it/s]

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
2026-05-14 10:23:03,493 - JAAT - INFO - Matching titles to codes...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[('25-4022.00', 0.921, -4.5, 'none')]

The returns a tuple of information: (TITLE CODE, MATCH SCORE, TITLE_VALUE, TITLE_FEATURES)

25-4022.00 = "Librarians and Media Collections Specialists"


The title "value" is the result of a model who assigns a numeric score to a title based on its seniority or experience level, ranging from -10 to 60. Title "features" are interesting attributes of the job title, if any, such as full-time vs part-time.

While the tools so far have been useful for matching information contained within job postings to standard coded taxonomies, we also may wish to extract information directly from the text itself. For this, we have built two tools for firm name extraction and wage data extraction Let's first look at firms..

In [19]:
FE = JAAT.FirmExtract()

Device set to use cuda

In [20]:
FE.get_firm(test_posting)

For ChunkPipeline using num_workers>0 is likely to result in errors since everything is iterable, setting `num_workers=1` to guarantee correctness.
/home/sjmeis/.local/lib/python3.10/site-packages/transformers/pipelines/token_classification.py:490: UserWarning: Tokenizer does not support real words, using fallback heuristic
  warnings.warn(

('NASJACKSONVILLE', 0.6029296517372131)

This matches well with "NAVAL AIR STATION JACKSONVILLE".

Let's also see if we can extract any wage information out of the job posting text.

In [21]:
WE = JAAT.WageExtract()

Device set to use cuda
Device set to use cuda
Device set to use cuda

In [22]:
WE.get_wage(test_posting)

For ChunkPipeline using num_workers>0 is likely to result in errors since everything is iterable, setting `num_workers=1` to guarantee correctness.

{'min': '18', 'max': '22', 'frequency': 'hourly'}

This checks out as well! These tools become even more useful when processing data at scale, and especially when structured metaata (e.g., firm or wage) is not readily available.

We introduce below one final tool, which is in beta and was introduced in the paper: AIMatch. With the rising prominence of AI in the workplace, it becomes very important to be able to map and extract the AI-related tasks and skills that may be required on the job. We built AIMatch to do this!

In [23]:
AI = JAAT.AIMatch()

2026-05-14 10:23:17,171 - JAAT - INFO - Initializing AIMatch...
2026-05-14 10:23:17,174 - JAAT - INFO - Preparing embeddings...

Batches:   0%|          | 0/308 [00:00<?, ?it/s]

2026-05-14 10:23:24,563 - JAAT - INFO - Setting up pipeline...
Device set to use cuda
2026-05-14 10:23:24,930 - JAAT - INFO - Finished.

In [24]:
AI.get_ai(test_posting)

([('Provides technical assistance across project management, policy, communication, research support, service development, training, and advisory roles.',
   'A6.G.6.k.14020'),
  ('Skilled in creating publishable content, infographics, and actionable deliverables, including CTRC orders.',
   'A6.F.10.i.13211'),
  ('Participates in and leads technical committees, meetings, and workshops for knowledge sharing and collaboration.',
   'A6.H.6.b.14717'),
  ('Proficient in office suite applications and various software packages with strong overall computer skills.',
   'A6.B.1.j.13939'),
  ('Ability to instill and employ best practices in software development and documentation, ensuring designs meet requirements.',
   'A6.F.0.n.16322'),
  ('Demonstrates a strong passion for technology and cybersecurity, with a commitment to continuous learning and teaching others.',
   'A6.J.0.k.15669'),
  ('Ability to prepare technical documentation, reports, and presentation materials, including briefings and publications.',
   'A6.A.5.n.11177'),
  ('Proficient in digital media and marketing strategy, including data analysis, analytics, visualization, and experience with digital advertising and client-facing roles.',
   'A6.A.13.a.21775'),
  ('Proficient in requirements gathering and verification analysis.',
   'A6.C.9.b.17754')],
 9,
 0.697,
 [0.828, 0.507, 0.748, 0.584, 0.601, 0.655, 0.565, 0.552, 0.556],
 [0.88, 0.88, 0.879, 0.918, 0.898, 0.898, 0.884, 0.892, 0.88])

The output of AIMatch requires some explanantion. In our building of the tool, we adopted a broad definition of "AI" and accordingly, built an "AI score" to help users quantify how "AI" the resulting outputs are.

The first part of the outputs, the tuples, stem from a custom-built taxonomy of AI-related tasks and skills (work in progress). Each of these matches is associated to an extraction score:

[0.828, 0.507, 0.748, 0.584, 0.601, 0.655, 0.565, 0.552, 0.556]

and a match score:

[0.88, 0.88, 0.879, 0.918, 0.898, 0.898, 0.884, 0.892, 0.88]

As you can see, some of the extraction scores are low, and we provide the user the flexibility to set thresholds or discard results as necessary. The match scores should be interpreted relatively. With our default model: Anything above 0.90 (out of 1) is a good match, as as we descend deeper into the 0.8 territory, the matches should be treated with less confidence.

As a final piece to the output, you can see that the 9 matches contribute to an average AI score of 0.697 - moderately high but not "frontier" work. We note that these measures are still in development and will be refined.

### Wrap-up

That was the end of the basic introduction of JAAT!

We will now move on to more advanced usage, namely on larger amounts of data, enabling you to replicate our work on USAJOBS.

## Scaling Up

Mow that we have introduced JAAT and its many functions, we will now demonstrate how to scale up its usage. The end goal of this process is the build structured, coded data files from large corpora of unstructured texts. These codes files are the foundation of the analyses we provide in the paper, and they are the potential future foundation for any ideas you might have!

For now, we will remain with the sample of 1000 USAJOBS postings. Later on, we provide the code to iterate through all of the USAJOBS monthly data, such that the true collection of monthly coded files can be constructed.

Here's a reminder of what the sample looks like:

In [25]:
df

,job_id,text,title,company
0,767977200,USAJOBS - Job Announcement family-of-overseas-...,Information Technology Specialist (Policy and ...,None
1,764460600,USAJOBS - Job Announcement family-of-overseas-...,Lead Security Guard,None
2,767905500,USAJOBS - Job Announcement family-of-overseas-...,Lead Recreation Assistant NF-02,None
3,765868200,USAJOBS - Job Announcement family-of-overseas-...,Medical Administrative Specialist,None
4,767266900,USAJOBS - Job Announcement family-of-overseas-...,PROGRAM MANAGER (INFORMATION RESOURCES),None
...,...,...,...,...
995,764122300,USAJOBS - Job Announcement family-of-overseas-...,PROGRAM ANALYST,None
996,764459600,USAJOBS - Job Announcement family-of-overseas-...,CYS Program Associate Technology Lab NF-03,None
997,763842000,USAJOBS - Job Announcement family-of-overseas-...,Licensed Practical Nurse,None
998,767090700,USAJOBS - Job Announcement family-of-overseas-...,SUPERVISORY EDUCATION SERVICES SPECIALIST,None
999,765471900,USAJOBS - Job Announcement family-of-overseas-...,Health System Specialist (Detail NTE 120 Days),None

As mentioned earlier, we have designed all of the JAAT tools for the primary use case of *batch processing* -- running JAAT on thousands to millions of job postings. To introduce this capability, first a few helpful utilities.

The first is text batching tool. In the case of our 1000 texts, it might not make too much sense, but if your corpus is much larger, you may want to process it in batches. An example of its usage is below.

In [26]:
# break down our data into chunks of 100 texts each
batches1 = JAAT.chunker(df.text.to_list(), size=100)
print(batches1)
print(len(list(batches1)))

# or, break down our data into chunks of any chosen size, say 42
batches2 = JAAT.chunker(df.text.to_list(), size=42)
print(batches2)
print(len(list(batches2)))

# what is in the return?
batches2 = JAAT.chunker(df.text.to_list(), size=42)
print("---------")
for i, batch in enumerate(batches2):
    print("Batch {}: {} postings".format(i, len(batch)), end = ', ')

<generator object chunker at 0x74b7de8f0cf0>
10
<generator object chunker at 0x74b7de8f3ae0>
24
---------
Batch 0: 42 postings, Batch 1: 42 postings, Batch 2: 42 postings, Batch 3: 42 postings, Batch 4: 42 postings, Batch 5: 42 postings, Batch 6: 42 postings, Batch 7: 42 postings, Batch 8: 42 postings, Batch 9: 42 postings, Batch 10: 42 postings, Batch 11: 42 postings, Batch 12: 42 postings, Batch 13: 42 postings, Batch 14: 42 postings, Batch 15: 42 postings, Batch 16: 42 postings, Batch 17: 42 postings, Batch 18: 42 postings, Batch 19: 42 postings, Batch 20: 42 postings, Batch 21: 42 postings, Batch 22: 42 postings, Batch 23: 34 postings,

The `chunker` utility breaks down potentially large collections of texts into a *generator* object, which is essentially a queue of the batches of texts. You only need to handle one at a time!

In addition, you can also use the following utility:

In [27]:
test_batch = list(JAAT.chunker(df.title.to_list(), size=10))[0] # take the first batch
JAAT.validate_inputs(test_batch)

['Information Technology Specialist (Policy and Planning)',
 'Lead Security Guard',
 'Lead Recreation Assistant NF-02',
 'Medical Administrative Specialist',
 'PROGRAM MANAGER (INFORMATION RESOURCES)',
 'Supervisory Interdisciplinary Engineer/Architect',
 'Registered Nurse - Health Promotion Disease Prevention Program Manager',
 'Instructional Systems Specialist (Analyst), GS-1750-12',
 'Health Technician (Telehealth Clinical)',
 'Psychology Technician']

This utility is helpful in validating that all elements of a batch (or any list) is valid for input to JAAT, i.e., not null or missing. This helps avoid errors down the road!

Now we can put all these tools together, and showcase batch functionality. Let's use TaskMatch!

In [28]:
batches = JAAT.chunker(df.text.to_list(), size=100) # smaller batches of 100 postings each

results = []
for i, batch in enumerate(batches):
    print("Processing batch {}...".format(i))
    validated_batch = JAAT.validate_inputs(batch) # comment out for quicker processing
    res = TM.get_tasks_batch(validated_batch)
    results.extend(res)

Processing batch 0...
Processing batch 1...
Processing batch 2...
Processing batch 3...
Processing batch 4...
Processing batch 5...
Processing batch 6...
Processing batch 7...
Processing batch 8...
Processing batch 9...

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Congratulations, you just processed 1000 job postings through TaskMatch!

As you can see, we captured the batch outputs of TaskMatch into `results`.

In [29]:
len(results)

1000

Each of the elements in this list corresponds 1:1 to the input job postings from our USAJOBS sample. For example:

In [30]:
df.iloc[123].text

'USAJOBS - Job Announcement family-of-overseas-employees-icon federal-employees-competitive-service-icon federal-employees-competitive-service-icon federal-employees-excepted-service-icon federal-employees-career-transition-icon individuals-with-disabilities-icon Created with Sketch. internal-to-an-agency-icon Created with Sketch. internal-to-an-agency-icon Created with Sketch. military-spouses-icon Created with Sketch. national-guard-and-reserves-icon Created with Sketch. native-americans-icon Created with Sketch. peace-corps-and-americorps-icons Open-to-the-public-icon senior-executive-service-icon se-other students-icon recent-graduates-icon veterans-icon special-hiring-authorities-icon land-and-base-management-icon Health Technician (Telehealth Clinical) (Advanced) Department of Veterans Affairs Veterans Health Administration Veterans Health Administration Help Summary The Health Technician (Telehealth Clinical) Advanced provides high level support, training, and advanced management of telehealth operations and is typically stationed at a clinical care delivery site (VA Medical Center, CBOC, VA Outreach Clinic, etc.). Help Overview Job canceled Open & closing dates 12/20/2023 to 01/04/2024 Salary $46,948 - $61,032 per year Pay scale & grade GS 7 Location 1 vacancy in the following location: Des Moines, IA 1 vacancy Remote job No Telework eligible No Travel Required 25% or less - You may be expected to travel for this position. Relocation expenses reimbursed No Appointment type Permanent Work schedule Full-time Service Excepted Promotion potential None Job family (Series) 0640 Health Aid And Technician Supervisory status No Security clearance Not Required Drug test Yes Position sensitivity and risk Non-sensitive (NS)/Low Risk Trust determination process Credentialing Suitability/Fitness Announcement number CBSY-12244608-24-JH Control number 765918400 Help This job is open to Internal to an agency Current federal employees of the hiring agency that posted the job announcement. Clarification from the agency This announcement is open to current, permanent VA employees. Help Duties The VA Midwest Health Care Network advocates for a Whole Health System of care in each of the Medical Centers. This is an approach to healthcare that empowers and equips people to take charge of their health and well-being and live their lives to the fullest. As an employee operating in a Whole Health System of care, you will operate in a model with three core elements, seeking to create a personalized health plan for each Veteran. This is done in the context of healing relationships and healing environments and a connection back to the Veteran\'s community. This aligns with the Veterans Health Administration (VHA) Mission Statement to Honor America\'s Veterans by providing exceptional health care that improves their health and well-being. Duties include, but are not limited to: - preparing the clinical environment, which may include preparing medical and telecommunications equipment to be used for clinical examination and treatment; -serving as a telepresenter, within scope of practice, during clinical video telehealth (CVT) and VA Video Connect (VVC) encounters including tasks such as establishing and maintaining video conferencing connections, making introductions between patient site and provider site, following instructions of a clinician to facilitate an effective clinical encounter; - serving as an imager and manager of clinical data for store and forward telehealth (SFT) clinical encounters including tasks such as capturing images, collecting data and transmitting them electronically for clinical review in accordance with VHA national guidelines; - taking measures to ensure patient care is delivered safely by following appropriate procedures for the cleaning of clinical equipment and the care environment while following all patient safety guidelines, protocols, and procedures; - completing standardized clinical questionnaires and templates within scope of training and applicable guidelines; - ensuring that patient privacy is protected by complying with all information security and patient privacy regulations; - receiving and scheduling requests for simple and complex intra-facility, and inter- facility telehealth appointments using an electronic resource-based scheduling system; - referring patients to providers for screening for Telehealth; - monitoring and maintaining schedules of rooms, patients, technologies, clinical providers and presenters as needed to ensure efficient telehealth operations;- providing patient education via approved materials;- supporting the Veteran in completing patient satisfaction surveys; - communicating effectively with clinical and administrative staff at the assigned local site and those located at remote sites of care; - coordinating and. or directly configuring, installing, troubleshooting, inventory management, cleaning, and performing minor routine maintenance of assigned telehealth technology; - ensuring assigned telehealth technologies are secured, ready for use, and accounted for by preparing and tracking maintenance work orders, information systems, inventory records, and communicating with National Telehealth Technology Help Desk to facilitate troubleshooting, repair, and coordination of replacement equipment as necessary. - providing education and training to Veterans, clinical staff and providers on the use of telehealth technologies and serving as a point of contact to answer questions and address concerns related to these technologies; - maintaining knowledge of and skill in applying an extensive body of rules, procedures, and operations in telehealth-related technologies and a variety of computer hardware and software used for telecommunications, data entry and retrieval, record maintenance, document and report generation- maintaining regular contact with other staff members and the Facility Telehealth Coordinator to work out process issues, equipment needs, problems, data collection and any other logistical issues; - arranging and completing test video calls with Veterans to prepare the Veterans for clinical encounters using telehealth technologies; ensuring information and resources are maintained for local and remote telehealth providers so they can effectively execute contingency and emergency plans; - completing other duties as assigned. Work Schedule : Full-time; Monday-Friday, 7:30 AM - 4:00 PM Telework : Not available Virtual: This is not a virtual position. Functional Statement # : 000000 Relocation/Recruitment Incentives : Not authorized Permanent Change of Station (PCS): Not authorized Fi nancial Disclosure Report: Not required Help Requirements Conditions of Employment You must be a U.S. Citizen to apply for this job. All applicants tentatively selected for VA employment in a testing designated position are subject to urinalysis to screen for illegal drug use prior to appointment. Applicants who refuse to be tested will be denied employment with VA. Selective Service Registration is required for males born after 12/31/1959. Must be proficient in written and spoken English. You may be required to serve a probationary period. Subject to background/security investigation. Selected applicants will be required to complete an online onboarding process. Must pass pre-employment physical examination. Participation in the seasonal influenza vaccination program is a requirement for all Department of Veterans Affairs Health Care Personnel (HCP). Participation in the Coronavirus Disease 2019 (COVID-19) vaccination program is a requirement for all Veterans Health Administration Health Care Personnel (HCP) - See "Additional Information" below for details. Qualifications All requirements must be met by the closing date of this announcement. Basic Requirements : United States Citizenship: Non-citizens may only be appointed when it is not possible to recruit qualified citizens in accordance with VA Policy. Experience and Education: Experience. One year of experience in a health care field that demonstrates the applicant\'s ability to perform the work or provides an understanding of the work such as but not limited to a medical or clinical assistant (or technician) or health technician. OR Education. Four academic years above high school leading to a bachelor\'s degree with courses related to the occupation. OR Experience/Education Combination. Equivalent combination of experience and education are qualifying for entry level for which both education and experience are acceptable. Examples are listed below: (a) Six months of experience in the health care field and two years of education above high school that included at least six semester hours in health care related courses such as, biological science, surgical technician courses, nursing assistant or other courses related to the position; or an associate\'s degree in a health care related field; or (b) Six months of experience in the health care field and successful completion of a course for health care technicians, hospital corpsmen, or medical service specialists given by the U.S. Armed Forces. Certification: None English Language Proficiency: A candidate will not be appointed under authority of 38 U.S.C. chapters 73 or 74, to serve in a direct patient-care capacity in VHA who is not proficient in written and spoken English. May qualify based on being covered by the Grandfathering Provision as described in the VA Qualification Standard for this occupation (only applicable to current VHA employees who are in this occupation and meet the criteria). Grade Determinations : GS-7 Health Technician (Telehealth Clinical) - Advanced Experience: One year of experience equivalent to the next lower grade level, GS-6. AND Demonstrated Knowledge, Skills, and Abilities: In addition to the experience above, the candidate must demonstrate all of the following KSAs. (a) Ability to use independent technical judgment to analyze, evaluate and resolve problems. (b) Knowledge of quality control and assurance procedures and principles of performance improvement. (c) Ability to function effectively between competing priorities. (d) Knowledge of proper maintenance and troubleshooting of telehealth equipment. (e) Ability to work with a team to provide technical guidance, plan, organize and coordinate activities of a health technician in order to effectively complete job duties of assignment such as distributing workload, monitoring the status and progress of work, monitoring accuracy of work. (f) Ability to assist in Health Technician (Telehealth Clinical) development, outcome management and strategic planning. (g) Ability to perform successful knowledge transfer regarding the use of telehealth technologies. References: VA HANDBOOK 5005/96 PART II APPENDIX G50 You will be asked to participate in a pre-employment examination or evaluation as part of the pre-employment process for this position. Questions about physical demands or environmental factors may be addressed at the time of evaluation or examination. Grandfathering Provision. All Health Technicians (Telehealth Clinical) employed in VHA in this occupation on the effective date of this qualification standard are considered to have met all qualification requirements for the title, series, and grade held. For employees who do not meet all the basic requirements required in this standard, but who met the qualifications applicable to the position at the time they were appointed to it, the following provisions apply: (1) Such employees may be reassigned, promoted up to and including the full performance (journeyman) level, or changed to lower grade within the occupation, but may not be promoted beyond the journeyman level or placed in supervisory or managerial positions. (2) Employees who are appointed on a temporary basis prior to the effective date of the qualification standard may not have their temporary appointment extended or be reappointed, on a temporary or permanent basis, until they fully meet the basic requirements of the standard. (3) If an employee who was retained (grandfathered) under this provision leaves that occupation, the employee loses protected status and must meet the full VA qualification standard requirements in effect at the time of re-entry to the occupation. Education IMPORTANT: A transcript must be submitted with your application if you are basing all or part of your qualifications on education. Note: Only education or degrees recognized by the U.S. Department of Education from accredited colleges, universities, schools, or institutions may be used to qualify for Federal employment. You can verify your education here: http://ope.ed.gov/accreditation/ . If you are using foreign education to meet qualification requirements, you must send a Certificate of Foreign Equivalency with your transcript in order to receive credit for that education. For further information, visit: http://www.ed.gov/about/offices/list/ous/international/usnei/us/edlite-visitus-forrecog.html . Additional information This job opportunity announcement may be used to fill additional vacancies. This position is in the Excepted Service and does not confer competitive status. VA encourages persons with disabilities to apply. The health-related positions in VA are covered by Title 38, and are not covered by the Schedule A excepted appointment authority. Pursuant to VHA Directive 1193.01, VHA health care personnel (HCP) are required to be fully vaccinated against COVID-19 subject to such accommodations as required by law (i.e., medical, religious or pregnancy). VHA HCPs do not include remote workers who only infrequently enter VHA locations. If selected, you will be required to be fully vaccinated against COVID-19 and submit documentation of proof of vaccination before your start date. The agency will provide additional information regarding what information or documentation will be needed and how you can request a legally required accommodation from this requirement using the reasonable accommodation process. If you are unable to apply online or need an alternate method to submit documents, please reach out to the Agency Contact listed in this Job Opportunity Announcement. Benefits A career with the U.S. government provides employees with a comprehensive benefits package. As a federal employee, you and your family will have access to a range of benefits that are designed to make your federal career very rewarding. Opens in a new window Learn more about federal benefits . Review our benefits Eligibility for benefits depends on the type of position you hold and whether your position is full-time, part-time or intermittent. Contact the hiring agency for more information on the specific benefits offered. How You Will Be Evaluated You will be evaluated for this job based on how well you meet the qualifications above. IN DESCRIBING YOUR EXPERIENCE, PLEASE BE CLEAR AND SPECIFIC. WE MAY NOT MAKE ASSUMPTIONS REGARDING YOUR EXPERIENCE. Your application, resume, C.V., and/or supporting documentation will be verified. Please follow all instructions carefully. Errors or omissions may affect consideration for employment. Experience refers to paid and unpaid experience, including volunteer work done through National Service programs (e.g., Peace Corps, AmeriCorps) and other organizations (e.g., professional; philanthropic; religions; spiritual; community; student; social). Volunteer work helps build critical competencies, knowledge, and skills and can provide valuable training and experience that translates directly to paid employment. You will receive credit for all qualifying experience, including volunteer experience. The Department of Veterans Affairs performs pre-employment reference checks as an assessment method used in the hiring process to verify information provided by a candidate (e.g., on resume or during interview or hiring process); gain additional knowledge regarding a candidate\'s abilities; and assist a hiring manager with making a final selection for a position. It is the policy of the VA to not deny employment to those that have faced financial hardships or periods of unemployment. Veterans and Transitioning Service Members : Please visit the VA for Vets site for career-search tools for Veterans seeking employment at VA, career development services for our existing Veterans, and coaching and reintegration support for military service members. Benefits A career with the U.S. government provides employees with a comprehensive benefits package. As a federal employee, you and your family will have access to a range of benefits that are designed to make your federal career very rewarding. Opens in a new window Learn more about federal benefits . Review our benefits Eligibility for benefits depends on the type of position you hold and whether your position is full-time, part-time or intermittent. Contact the hiring agency for more information on the specific benefits offered. Required Documents As a new or existing federal employee, you and your family may have access to a range of benefits. Your benefits depend on the type of position you have - whether you\'re a permanent, part-time, temporary or an intermittent employee. You may be eligible for the following benefits, however, check with your agency to make sure you\'re eligible under their policies. To apply for this position, you must provide a complete Application Package which includes: Resume SF-50/ Notification of Personnel Action The following documents are accepted, and may be required if applicable to your eligibility and/or qualifications for this position. Please use this checklist to ensure you have included all documents required for your application, such as a copy of your transcript (if using education to qualify), SF-50\'s (current/former Federal employees), etc. Cover Letter VA 10-2850C Application for Associated Health Occupations Knowledge, Skills, and Abilities Statement Resume SF-50/ Notification of Personnel Action Transcript If you are relying on your education to meet qualification requirements: Education must be accredited by an accrediting institution recognized by the U.S. Department of Education in order for it to be credited towards qualifications. Therefore, provide only the attendance and/or degrees from schools accredited by accrediting institutions recognized by the U.S. Department of Education . Failure to provide all of the required information as stated in this vacancy announcement may result in an ineligible rating or may affect the overall rating. How to Apply All applicants are encouraged to apply online. To apply for this position, you must complete the full questionnaire and submit the documentation specified in the Required Documents section below. The complete application package must be submitted by 11:59 PM (ET) on 01/04/2024 to receive consideration. To preview the questionnaire click https://apply.usastaffing.gov/ViewQuestionnaire/12244608 . To begin, click Apply Online to create a USAJOBS account or log in to your existing account. Follow the prompts to select your USA JOBS resume and/or other supporting documents and complete the occupational questionnaire. Click Submit My Answers to submit your application package. NOTE: It is your responsibility to ensure your responses and appropriate documentation is submitted prior to the closing date. To verify your application is complete, log into your USA JOBS account, https://my.usajobs.gov/Account/Login , select the Application Status link and then select the more information link for this position. The Details page will display the status of your application, the documentation received and processed, and any correspondence the agency has sent related to this application. Your uploaded documents may take several hours to clear the virus scan process. To return to an incomplete application, log into your USA JOBS account and click Update Application in the vacancy announcement

In [31]:
results[123]

[('18447',
  'Develop and implement individualized plans for health care management.'),
 ('529', 'Set up equipment and prepare medical treatment rooms.'),
 ('22814', 'Operate digital picture archiving communications systems.'),
 ('4266',
  'Assemble, clean, or maintain equipment or materials for patient use.'),
 ('18389',
  'Develop treatment plans, based on scientific rationale, standards of care, and professional practice guidelines.'),
 ('18097',
  'Develop or implement policies or practices to ensure the privacy, confidentiality, or security of patient information.'),
 ('5074', 'Answer telephones and schedule appointments.'),
 ('1818',
  'Refer patients to other health professionals or agencies when appropriate.'),
 ('18091',
  'Plan, install, repair, or troubleshoot telehealth technology applications or systems in homes.'),
 ('20417',
  'Design patient education programs that include information required to make informed health care and treatment decisions.'),
 ('5435', 'Measure and assess customer and employee satisfaction.'),
 ('17668',
  'Coordinate communication between patients, family members, medical staff, administrative staff, or regulatory agencies.'),
 ('18091',
  'Plan, install, repair, or troubleshoot telehealth technology applications or systems in homes.'),
 ('18091',
  'Plan, install, repair, or troubleshoot telehealth technology applications or systems in homes.'),
 ('18091',
  'Plan, install, repair, or troubleshoot telehealth technology applications or systems in homes.'),
 ('4133', 'Prepare and position patients for testing.'),
 ('11074', 'Maintain or update emergency response plans or procedures.'),
 ('9583',
  'Assign duties to other staff and give instructions regarding work methods and routines.'),
 ('3073',
  'Evaluate technical specifications to identify equipment or systems best suited for intended use and possible purchase, based on specifications, user needs, or technical requirements.'),
 ('21996',
  'Specify, coordinate, or conduct quality control or quality assurance programs or procedures.'),
 ('18091',
  'Plan, install, repair, or troubleshoot telehealth technology applications or systems in homes.'),
 ('4082',
  'Supervise and coordinate activities of technicians and technical assistants.'),
 ('7762',
  'Coordinate and direct work of nurses, medical technicians, and other health care providers.'),
 ('18871',
  'Select qualified job applicants or refer them to managers, making hiring recommendations when appropriate.')]

With this structure, we can easily and quickly "wrap up" results and map them back to the original posting IDs:

In [32]:
codes = [";".join([c[0] for c in x]) for x in results]
result_df = pd.DataFrame()
result_df["job_id"] = df["job_id"]
result_df["tasks"] = codes
result_df

        job_id                                              tasks
0    767977200  16156;16270;18595;2785;14623;9719;22;21702;213...
1    764460600  22942;23159;22011;8480;2703;2775;2133;9809;183...
2    767905500          4480;2671;21987;2791;5258;7236;1082;17521
3    765868200                             4268;21876;14339;18871
4    767266900  8469;16169;7663;14758;3481;21778;21496;15677;1...
..         ...                                                ...
995  764122300  3751;1554;15649;7379;7572;1506;14680;9007;7205...
996  764459600  1914;21408;22497;4565;20130;844;6480;663;1326;...
997  763842000  18308;17286;22864;17094;19015;17326;2637;17199...
998  767090700  100;1862;23169;18595;3395;15258;15652;6979;567...
999  765471900  514;7316;18317;103;5158;3401;3401;5522;61;2289...

[1000 rows x 2 columns]

And voila, you have now gone from job postings to structured, coded data using JAAT. A similar processing can be followed for all JAAT modules, you can test them out below!

In [33]:
all_texts = df.text.to_list()
skills = SM.get_skills_batch(all_texts)
codes = [";".join([c[1] for c in x]) for x in skills]
result_df["skills"] = codes

In [34]:
titles = TiM.get_title(df.title.to_list())
codes = [x[0] for x in titles]
result_df["title"] = codes

2026-05-14 10:26:10,750 - JAAT - INFO - Extracting title values...

Processing:   0%|          | 0/1000 [00:00<?, ?it/s]

2026-05-14 10:26:13,343 - JAAT - INFO - Extracting title features...

Processing:   0%|          | 0/63 [00:00<?, ?it/s]

2026-05-14 10:26:15,629 - JAAT - INFO - Matching titles to codes...

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [37]:
firms = FE.get_firm_batch(all_texts)
temp = [x[0] for x in firms]
result_df["firm"] = temp

In [39]:
wages = WE.get_wage_batch(all_texts)
temp = ["{}-{}-{}".format(str(x["min"]), str(x["max"]), str(x["frequency"])) if x is not None else None for x in wages]
result_df["wage"] = temp

In [41]:
ai = AI.get_ai_batch(all_texts)
codes = [";".join([c[1] for c in x]) for x in ai[0]]
result_df["AI"] = codes

And with that, we now have a complete coded dataset with the JAAT-provided features, mapped to each of the original 1000 job postings from the USAJOBS sample.

In [42]:
result_df

,job_id,tasks,skills,title,firm,wage,AI
0,767977200,16156;16270;18595;2785;14623;9719;22;21702;213...,S2.3;S2.9;S1.9;T3.1;S1.5;S3.1;S3.1;S1.5;S4.7;S...,15-1232.00,None,"76,990-100,084-annually",A6.G.5.n.12305;A6.A.15.k.16790;A6.I.1.c.18983;...
1,764460600,22942;23159;22011;8480;2703;2775;2133;9809;183...,T3.1;S8.7;S3.4;S3.3;S1.8,33-9032.00,None,"46,696-60,703-annually",A6.A.4.b.12431
2,767905500,4480;2671;21987;2791;5258;7236;1082;17521,S3.4;S1.1;S8.0;S1.2;S1.14;S1.8,39-3091.00,None,17-19-hourly,
3,765868200,4268;21876;14339;18871,T4.2;T5.2;S6.2;S1.7,29-2072.00,None,"69,107-89,835-annually",A6.C.2.g.13502;A6.G.6.k.11216;A6.A.4.d.13737
4,767266900,8469;16169;7663;14758;3481;21778;21496;15677;1...,S4.4;T2.2;T2.3;S2.7;S2.8;S2.7;S4.1,15-1299.09,None,"112,015-145,617-annually",A6.A.13.f.11619;A6.F.8.d.11570;A6.G.2.j.21158;...
...,...,...,...,...,...,...,...
995,764122300,3751;1554;15649;7379;7572;1506;14680;9007;7205...,S1.5;S1.5;S1.0;T3.1;T3.1;S4.2;S4.2;S4.2;T4.2;S...,13-1111.00,TRANSPORTATION SECURITY,"71,099-109,908-annually",A6.D.2.d.13930;A6.B.0.d.14515;A6.J.9.b.23286;A...
996,764459600,1914;21408;22497;4565;20130;844;6480;663;1326;...,S4.8;T2.2;S4.8;T1.3;T1.3;T1.3;S6.2,19-4099.01,None,"37,696-49,009-annually",A6.A.6.h.10945;A6.G.4.g.17559;A6.B.1.l.11427;A...
997,763842000,18308;17286;22864;17094;19015;17326;2637;17199...,S2.2;S3.2;S3.1;T3.2;T4.1;S3.2;S2.8;S1.3,29-2061.00,VETERANS HEALTH ADMIN,"60,958-79,241-annually",
998,767090700,100;1862;23169;18595;3395;15258;15652;6979;567...,S4.8;S4.1;T3.2;T2.4;S4.8;S2.7;S4.1;S4.3;T6.6;T4.2,11-9032.00,None,"69,107-89,835-annually",A6.F.6.c.11235;A6.F.6.c.11235;A6.B.2.z.20348;A...
999,765471900,514;7316;18317;103;5158;3401;3401;5522;61;2289...,S1.5;S2.8;S2.8;S1.2;S4.4;S2.0;S4.4;S2.0;S6.2;S...,19-5011.00,AFFAIRS,"93,858-145,090-annually",A6.G.2.c.13137;A6.B.0.l.12368;A6.B.0.l.12368

## Running JAAT on the USAJOBS Corpus

Moving beyond the 1000 posting sample with which we have been working, we are now equipped to run JAAT on all of the USAJOBS data. This is simplified by the ability stream all of the USAJOBS data from our open-source Hugging Face repository.

We will walk you through the basic steps below. Please note that depending on your setup and hardware constraints, you may need to modify the pipeline slightly. In addition, some of the processing below may take very long (USAJOBS is over three million postings), so plan accordingly! We also highly recommend moving some of the logic to shell scripts -- this Juypter Notebook is good for demonstration, but not necessarily for large-scale processing!

In [52]:
from datasets import get_dataset_split_names
from tqdm.auto import tqdm

First let's explore a little of the makeup of our USAJOBS repository.

In [47]:
splits = get_dataset_split_names("loyoladatamining/usajobs", "postings")
print(splits)

['2026_03', '2026_02', '2026_01', '2025_12', '2025_11', '2025_10', '2025_09', '2025_08', '2025_07', '2025_06', '2025_05', '2025_04', '2025_03', '2025_02', '2025_01', '2024_12', '2024_11', '2024_10', '2024_09', '2024_08', '2024_07', '2024_06', '2024_05', '2024_04', '2024_03', '2024_02', '2024_01', '2023_12', '2023_11', '2023_10', '2023_09', '2023_08', '2023_07', '2023_06', '2023_05', '2023_04', '2023_03', '2023_02', '2023_01', '2022_12', '2022_11', '2022_10', '2022_09', '2022_08', '2022_07', '2022_06', '2022_05', '2022_04', '2022_03', '2022_02', '2022_01', '2021_12', '2021_11', '2021_10', '2021_09', '2021_08', '2021_07', '2021_06', '2021_05', '2021_04', '2021_03', '2021_02', '2021_01', '2020_12', '2020_11', '2020_10', '2020_09', '2020_08', '2020_07', '2020_06', '2020_05', '2020_04', '2020_03', '2020_02', '2020_01', '2019_12', '2019_11', '2019_10', '2019_09', '2019_08', '2019_07', '2019_06', '2019_05', '2019_04', '2019_03', '2019_02', '2019_01', '2018_12', '2018_11', '2018_10', '2018_09', '2018_08', '2018_07', '2018_06', '2018_05', '2018_04', '2018_03', '2018_02', '2018_01', '2017_12', '2017_11', '2017_10']

As you can see, the dataset repository is organized into a number of "splits", or partitions, of the larger corpus. Naturally, this is done by month.

We can use the *stream* feature of the dataset loader to avoid having to store the entire dataset at once in memory. Note that this requires an active internet connection.

In [50]:
sample_stream = load_dataset("loyoladatamining/usajobs", "postings", split="2017_10", streaming=True)

In [51]:
# iterate through a few examples from the dataset stream
idx = 0
for posting in sample_stream:
    if idx == 10:
        break
    print(posting["job_id"])
    idx += 1

382487500
453902600
453256800
453669700
455916400
463982300
453924400
452693700
462547700
458246500

With this setup at our disposal, we can now set up a "pipeline" to iterate through all of the splits, stream the data as needed, and then process this data through our JAAT modules. Here is an example with TaskMatch (this will run for a while, so by default, we break after the first split is processed).

In [53]:
master_results = {}
for s in splits:
    print(s)
    stream = load_dataset("loyoladatamining/usajobs", "postings", split=s, streaming=True)

    # temporary data structures to hold the streamed data
    job_ids = []
    job_postings = []
    job_titles = []
    for posting in tqdm(stream):
        job_ids.append(posting["job_id"])
        job_postings.append(posting["text"])
        job_titles.append(posting["title"])

    monthly_df = pd.DataFrame()
    monthly_df["job_id"] = job_ids
    
    # now process in batch mode
    results = TM.get_tasks_batch(job_postings)
    codes = [";".join([c[0] for c in x]) for x in results]
    monthly_df["tasks"] = codes

    titles = TiM.get_title(job_titles)
    codes = [x[0] for x in titles]
    monthly_df["title"] = codes

    # ...
    # and likewise for other JAAT modules

    master_results[s] = monthly_df

    # manual cleanup - optional, but good to do
    del job_ids[:]
    del job_postings[:]
    del job_titles[:]

    # uncoment for full run!
    break

2026_03

0it [00:00, ?it/s]

2026-05-14 11:04:25,787 - JAAT - INFO - Extracting title values...

Processing:   0%|          | 0/14145 [00:00<?, ?it/s]

2026-05-14 11:04:54,721 - JAAT - INFO - Extracting title features...

Processing:   0%|          | 0/885 [00:00<?, ?it/s]

2026-05-14 11:05:23,532 - JAAT - INFO - Matching titles to codes...

Batches:   0%|          | 0/443 [00:00<?, ?it/s]

With this finished, you will have a data structure that maps each month to its respective results DataFrame:

In [59]:
master_results

{'2026_03':           job_id                                              tasks  \
 0      816513500  5177;5177;9860;16519;18788;5177;20812;1452;299...
 1      833603300                                          2127;8568
 2      833725700  2702;1649;2702;1649;21647;18578;2702;3363;2388...
 3      833226500  2702;1649;2702;1649;21647;18578;2702;3363;2388...
 4      834963900  14304;15453;19920;15452;14574;22276;22088;1475...
 ...          ...                                                ...
 14140  860094700   4543;657;20437;8149;5269;14457;12895;16977;16977
 14141  860953100  20432;17;20432;17;2402;11178;2052;6998;8872;25...
 14142  860875700  23583;21193;23583;21193;23168;5049;23457;22987...
 14143  859781300  9658;23121;9491;8053;11192;11198;22261;5053;95...
 14144  860084700  23118;18856;983;14632;17603;8419;8568;8830;857...

             title
 0      49-3042.00
 1      15-1221.00
 2      13-1141.00
 3      13-1141.00
 4      51-8093.00
 ...           ...
 14140  19-1031.03
 14141  43-3071.00
 14142  39-3091.00
 14143  35-2012.00
 14144  11-3031.00

 [14145 rows x 3 columns]}

Now with all of the saved results, we save the DataFrames to flat files, for use in downstream ETL and analysis piplines.

In [56]:
#for month in master_results:
#    master_results[month].to_csv("/path/to/output/{}.csv".format(month), index=False) # change path to your desired location!

### Wrap up

This concludes the full demonstration on how to use JAAT, from single uses to full scale data processing pipelines on large text corpora. Follow along our other demo notebooks for a snapshot and replication code of how we evaluated JAAT with the help of modern LLMs, as well as some interesting use cases of JAAT.